set(IMAGO_VERSION "2")

if(BUILD_VERSION)
   set(IMAGO_BUILD_VERSION ${BUILD_VERSION})
else()
   set(IMAGO_BUILD_VERSION 0)
endif()

set(IMAGO_VERSION_SUFFIX "dev")

set(IMAGO_VERSION_EXT "${IMAGO_VERSION}.${IMAGO_BUILD_VERSION}-${IMAGO_VERSION_SUFFIX}") # ${PACKAGE_SUFFIX}")