#!/bin/sh
# post-commit
# version file
file="git_commit.h"
path='./version'
sm="_"
file_def=`echo _$file$sm|tr "." "_"|tr "[:lower:]" "[:upper:]"`
echo "#ifndef $file_def" > $path/$file
echo "#define $file_def" >> $path/$file
echo " " >> $path/$file
echo "static const char *git_commit_str = \""`git log --pretty=oneline -n1`"\";" >> $path/$file
echo "static const char *git_date_of_commit_str = \""`git log -1 | grep "^Date:"`"\";" >> $path/$file
echo " " >> $path/$file
echo "#endif /* $file_def */" >> $path/$file

# Output message
echo "--- Git commit is written to $file ---"
echo "--- !!! NOW PLEASE RECOMPILE YOUR PROJECT TO TAKE EFFECT !!! ---"

#end