import os
from os.path import join

Import('env')

SConscript('jni/SConscript')
Import('imagojni')

classes = env.Java('classes', 'src')
imagojar = env.Jar(target = 'imago.jar', source = classes)
Requires(imagojar, imagojni)

path = join(env['OUTPUT_DIR'], 'jimago')
env.Install(path, imagojar)
env.Alias('jimago', path)
env.Alias('all', path)
if env['OS'] == 'Mac':
    path = join(path, 'lib', env['OS'], env['MACOSX_VERSION'])
else:
    path = join(path, 'lib', env['OS'], env['TARGET_BITS'])

env.Install(path, imagojni)
env.Alias('jimago', path)
env.Alias('all', path)

Export('imagojni')
Export('imagojar')
