import os

Import('env')

Import('imago_c_static')
Import('imago_h')
Import('libimago')


c_dir = os.path.dirname(str(imago_h))
include_dirs = [
c_dir,
'../../imago/src'
]

jnienv = env.Clone()
jnienv.Append(CPPPATH = include_dirs)
jnienv.Append(LIBS = [imago_c_static, libimago])

builddir = env['BUILDDIR']

imagojni_obj = jnienv.SharedObject(target = os.path.join(builddir, 'imagojni'), source = ['imagojni.cpp'])

imagojni = jnienv.SharedLibrary(target = os.path.join(builddir, 'imagojni'), source = imagojni_obj)
Depends(imagojni, imago_c_static)

Export('imagojni')
