if(SYSTEM_NAME STREQUAL "Win")
	include(BuildOptionsWin)
elseif(SYSTEM_NAME STREQUAL "Linux")
	include(BuildOptionsLinux)
elseif(SYSTEM_NAME STREQUAL "Mac")
	include(BuildOptionsMac)
endif()

set(THIRD_PARTY_DIR ${CMAKE_SOURCE_DIR}/third_party)

find_package(Java)

set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP TRUE)
include(InstallRequiredSystemLibraries)

string(TOLOWER ${CMAKE_SYSTEM_NAME} IMAGO_SYSTEM_NAME_LOWER)
string(TOLOWER ${CMAKE_SYSTEM_PROCESSOR} IMAGO_SYSTEM_PROCESSOR_LOWER)
if (IMAGO_SYSTEM_PROCESSOR_LOWER STREQUAL "amd64")
	set(IMAGO_SYSTEM_PROCESSOR_LOWER "x86_64")
endif()
set(IMAGO_DIST_DIR ${CMAKE_SOURCE_DIR}/dist)
if (WIN32)
	find_program(CP cp PATHS ENV{PATH})
	if (CP)
		set(COPY_COMMAND cp)
	else()
		set(COPY_COMMAND copy)
	endif()
else()
	set(COPY_COMMAND cp)
endif()
file(TO_NATIVE_PATH "/" SEP)
