name: CI

env:
  OS_NAME_MAPPING_JSON: '{"ubuntu": "linux", "windows": "windows", "macos": "macos"}'

on:
  push:
    branches:
      - master
    tags:
      - 'imago-*'
  workflow_dispatch:
  pull_request:
  repository_dispatch:

jobs:
  build_x86_64:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos, ubuntu, windows ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: false
          fetch-depth: 500
      - name: Git fetch tags
        run: git fetch --tags -f
      - name: Build Linux
        if: ${{ matrix.os == 'ubuntu' }}
        uses: docker://epmlsop/buildpack-centos7:latest
        with:
          args: >
            /bin/sh -c "
            mkdir build &&
            cd build &&
            cmake ..
            cmake --build . --config Release --target all -- -j $(nproc) &&
            ctest --verbose
            "
      - name: Build macOS
        if: ${{ matrix.os == 'macos' }}
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release --target all -- -j $(sysctl -n hw.logicalcpu)
          ctest --verbose
      - name: Build Windows
        if: ${{ matrix.os == 'windows' }}
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release --target ALL_BUILD
          ctest --verbose -C Release
